//
//  EmojiRegistry.swift
//  tte
//
//  Created by Alex Young on 11/25/25.
//

import Foundation

/// Registry of emoji shortcodes and their corresponding emoji characters.
/// Uses Discord-compatible shortcode format (e.g., ":fire:" -> 🔥)
class EmojiRegistry {
    static let shared = EmojiRegistry()

    /// Dictionary mapping shortcodes to emoji characters
    let mappings: [String: String] = [
        // Smileys & Emotion
        ":grinning:": "😀",
        ":smiley:": "😃",
        ":smile:": "😄",
        ":grin:": "😁",
        ":laughing:": "😆",
        ":sweat_smile:": "😅",
        ":joy:": "😂",
        ":rofl:": "🤣",
        ":relaxed:": "☺️",
        ":blush:": "😊",
        ":innocent:": "😇",
        ":slight_smile:": "🙂",
        ":upside_down:": "🙃",
        ":wink:": "😉",
        ":relieved:": "😌",
        ":heart_eyes:": "😍",
        ":kissing_heart:": "😘",
        ":kissing:": "😗",
        ":kissing_smiling_eyes:": "😙",
        ":kissing_closed_eyes:": "😚",
        ":yum:": "😋",
        ":stuck_out_tongue:": "😛",
        ":stuck_out_tongue_closed_eyes:": "😝",
        ":stuck_out_tongue_winking_eye:": "😜",
        ":zany_face:": "🤪",
        ":face_with_raised_eyebrow:": "🤨",
        ":face_with_monocle:": "🧐",
        ":nerd:": "🤓",
        ":sunglasses:": "😎",
        ":star_struck:": "🤩",
        ":partying_face:": "🥳",
        ":smirk:": "😏",
        ":unamused:": "😒",
        ":disappointed:": "😞",
        ":pensive:": "😔",
        ":worried:": "😟",
        ":confused:": "😕",
        ":slight_frown:": "🙁",
        ":frowning2:": "☹️",
        ":persevere:": "😣",
        ":confounded:": "😖",
        ":tired_face:": "😫",
        ":weary:": "😩",
        ":pleading_face:": "🥺",
        ":cry:": "😢",
        ":sob:": "😭",
        ":triumph:": "😤",
        ":angry:": "😠",
        ":rage:": "😡",
        ":face_with_symbols_over_mouth:": "🤬",
        ":exploding_head:": "🤯",
        ":flushed:": "😳",
        ":scream:": "😱",
        ":fearful:": "😨",
        ":cold_sweat:": "😰",
        ":disappointed_relieved:": "😥",
        ":sweat:": "😓",
        ":hugging:": "🤗",
        ":thinking:": "🤔",
        ":face_with_hand_over_mouth:": "🤭",
        ":yawning_face:": "🥱",
        ":shushing_face:": "🤫",
        ":lying_face:": "🤥",
        ":no_mouth:": "😶",
        ":neutral_face:": "😐",
        ":expressionless:": "😑",
        ":grimacing:": "😬",
        ":roll_eyes:": "🙄",
        ":hushed:": "😯",
        ":frowning:": "😦",
        ":anguished:": "😧",
        ":open_mouth:": "😮",
        ":astonished:": "😲",
        ":sleeping:": "😴",
        ":drooling_face:": "🤤",
        ":sleepy:": "😪",
        ":dizzy_face:": "😵",
        ":zipper_mouth:": "🤐",
        ":woozy_face:": "🥴",
        ":nauseated_face:": "🤢",
        ":face_vomiting:": "🤮",
        ":sneezing_face:": "🤧",
        ":mask:": "😷",
        ":thermometer_face:": "🤒",
        ":head_bandage:": "🤕",
        ":money_mouth:": "🤑",
        ":cowboy:": "🤠",
        ":smiling_imp:": "😈",
        ":imp:": "👿",
        ":japanese_ogre:": "👹",
        ":japanese_goblin:": "👺",
        ":clown:": "🤡",
        ":poop:": "💩",
        ":ghost:": "👻",
        ":skull:": "💀",
        ":skull_crossbones:": "☠️",
        ":alien:": "👽",
        ":space_invader:": "👾",
        ":robot:": "🤖",
        ":jack_o_lantern:": "🎃",
        ":smiley_cat:": "😺",
        ":smile_cat:": "😸",
        ":joy_cat:": "😹",
        ":heart_eyes_cat:": "😻",
        ":smirk_cat:": "😼",
        ":kissing_cat:": "😽",
        ":scream_cat:": "🙀",
        ":crying_cat_face:": "😿",
        ":pouting_cat:": "😾",

        // Gestures & People
        ":wave:": "👋",
        ":raised_hand:": "✋",
        ":vulcan:": "🖖",
        ":ok_hand:": "👌",
        ":v:": "✌️",
        ":crossed_fingers:": "🤞",
        ":metal:": "🤘",
        ":call_me:": "🤙",
        ":point_left:": "👈",
        ":point_right:": "👉",
        ":point_up_2:": "👆",
        ":point_down:": "👇",
        ":point_up:": "☝️",
        ":thumbsup:": "👍",
        ":thumbsdown:": "👎",
        ":fist:": "✊",
        ":facepunch:": "👊",
        ":left_facing_fist:": "🤛",
        ":right_facing_fist:": "🤜",
        ":clap:": "👏",
        ":raised_hands:": "🙌",
        ":open_hands:": "👐",
        ":palms_up_together:": "🤲",
        ":handshake:": "🤝",
        ":pray:": "🙏",
        ":writing_hand:": "✍️",
        ":nail_care:": "💅",
        ":selfie:": "🤳",
        ":muscle:": "💪",
        ":mechanical_arm:": "🦾",
        ":mechanical_leg:": "🦿",
        ":leg:": "🦵",
        ":foot:": "🦶",
        ":ear:": "👂",
        ":nose:": "👃",
        ":brain:": "🧠",
        ":eyes:": "👀",
        ":eye:": "👁️",
        ":tongue:": "👅",
        ":lips:": "👄",

        // Monkeys
        ":see_no_evil:": "🙈",
        ":hear_no_evil:": "🙉",
        ":speak_no_evil:": "🙊",

        // Hearts
        ":heart:": "❤️",
        ":orange_heart:": "🧡",
        ":yellow_heart:": "💛",
        ":green_heart:": "💚",
        ":blue_heart:": "💙",
        ":purple_heart:": "💜",
        ":black_heart:": "🖤",
        ":brown_heart:": "🤎",
        ":white_heart:": "🤍",
        ":broken_heart:": "💔",
        ":heart_exclamation:": "❣️",
        ":two_hearts:": "💕",
        ":revolving_hearts:": "💞",
        ":heartbeat:": "💓",
        ":heartpulse:": "💗",
        ":sparkling_heart:": "💖",
        ":cupid:": "💘",
        ":gift_heart:": "💝",
        ":heart_decoration:": "💟",

        // Symbols
        ":100:": "💯",
        ":fire:": "🔥",
        ":sparkles:": "✨",
        ":star:": "⭐",
        ":star2:": "🌟",
        ":dizzy:": "💫",
        ":boom:": "💥",
        ":anger:": "💢",
        ":sweat_drops:": "💦",
        ":dash:": "💨",
        ":hole:": "🕳️",
        ":speech_balloon:": "💬",
        ":eye_in_speech_bubble:": "👁️‍🗨️",
        ":thought_balloon:": "💭",
        ":zzz:": "💤",

        // Popular Objects & Activities
        ":tada:": "🎉",
        ":confetti_ball:": "🎊",
        ":rocket:": "🚀",
        ":trophy:": "🏆",
        ":medal:": "🏅",
        ":first_place:": "🥇",
        ":second_place:": "🥈",
        ":third_place:": "🥉",
        ":soccer:": "⚽",
        ":basketball:": "🏀",
        ":football:": "🏈",
        ":baseball:": "⚾",
        ":tennis:": "🎾",
        ":8ball:": "🎱",
        ":pizza:": "🍕",
        ":hamburger:": "🍔",
        ":fries:": "🍟",
        ":hotdog:": "🌭",
        ":taco:": "🌮",
        ":burrito:": "🌯",
        ":beer:": "🍺",
        ":beers:": "🍻",
        ":wine_glass:": "🍷",
        ":coffee:": "☕",
        ":tea:": "🍵",
        ":cake:": "🍰",
        ":birthday:": "🎂",
        ":cookie:": "🍪",

        // Gestures (additional)
        ":ok:": "🆗",
        ":new:": "🆕",
        ":free:": "🆓",
        ":cool:": "🆒",
        ":sos:": "🆘",
        ":up:": "🆙",
        ":vs:": "🆚",

        // Flags (common)
        ":checkered_flag:": "🏁",
        ":triangular_flag_on_post:": "🚩",
        ":crossed_flags:": "🎌",
        ":rainbow_flag:": "🏳️‍🌈",

        // Additional common Discord emojis
        ":shrug:": "🤷",
        ":facepalm:": "🤦",
        ":ping_pong:": "🏓",
        ":microphone:": "🎤",
        ":headphones:": "🎧",
        ":video_game:": "🎮",
        ":guitar:": "🎸",
        ":musical_note:": "🎵",
        ":notes:": "🎶",
        ":bell:": "🔔",
        ":no_bell:": "🔕",
        ":mega:": "📣",
        ":loudspeaker:": "📢",
        ":book:": "📖",
        ":books:": "📚",
        ":pencil:": "📝",
        ":bulb:": "💡",
        ":mag:": "🔍",
        ":mag_right:": "🔎",
        ":lock:": "🔒",
        ":unlock:": "🔓",
        ":key:": "🔑",
        ":hammer:": "🔨",
        ":wrench:": "🔧",
        ":nut_and_bolt:": "🔩",
        ":gear:": "⚙️",
        ":link:": "🔗",
        ":chains:": "⛓️",
        ":warning:": "⚠️",
        ":no_entry:": "⛔",
        ":white_check_mark:": "✅",
        ":x:": "❌",
        ":o:": "⭕",
        ":question:": "❓",
        ":grey_question:": "❔",
        ":grey_exclamation:": "❕",
        ":exclamation:": "❗",
        ":heavy_plus_sign:": "➕",
        ":heavy_minus_sign:": "➖",
        ":heavy_division_sign:": "➗",
        ":heavy_multiplication_x:": "✖️",
        ":arrow_left:": "⬅️",
        ":arrow_right:": "➡️",
        ":arrow_up:": "⬆️",
        ":arrow_down:": "⬇️"
    ]

    /// Cached sorted list of all shortcodes for efficient autocomplete lookups
    private lazy var sortedShortcuts: [String] = {
        return Array(mappings.keys).sorted()
    }()

    private init() {}

    /// Returns the emoji for a given shortcode.
    /// - Parameter shortcut: The emoji shortcode (e.g., ":fire:")
    /// - Returns: The emoji character, or nil if not found
    func getEmoji(for shortcut: String) -> String? {
        return mappings[shortcut]
    }

    /// Returns all available shortcodes in alphabetical order.
    /// Uses a cached sorted list for performance.
    /// - Returns: Sorted array of shortcode strings
    func getAllShortcuts() -> [String] {
        return sortedShortcuts
    }
}
